# Generated by Django 5.1.4 on 2025-01-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='qualification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('dentist', 'Dentist'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('lab_technician', 'Lab Technician'), ('radiology_staff', 'Radiology Staff'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin')], max_length=50),
        ),
    ]
