# Generated by Django 5.1.4 on 2025-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
