# Generated by Django 5.1.4 on 2025-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visit_visit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_number',
            new_name='visit_id',
        ),
    ]
