# Generated by Django 5.1.4 on 2025-02-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_visit_number_visit_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
