# Generated by Django 5.1.4 on 2025-02-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_visit_visit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_id',
            new_name='visit_number',
        ),
    ]
