# Generated by Django 5.1.4 on 2025-02-12 13:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_visit_id_visit_visit_number'),
        ('users', '0004_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Company',
                'verbose_name_plural': 'Insurance Companies',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_provider',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[core.models.validate_dob]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.department'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_number',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insurancecompany')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('test', 'Test'), ('medicine', 'Medicine'), ('service', 'Service'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_companies', models.ManyToManyField(blank=True, related_name='covered_items', to='core.insurancecompany')),
            ],
            options={
                'verbose_name': 'Hospital Item',
                'verbose_name_plural': 'Hospital Items',
            },
        ),
    ]
