# Generated by Django 5.1.4 on 2025-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_insurancecompany_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
