# Generated by Django 5.1.4 on 2025-02-14 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_invoiceitem_type_alter_paymentitem_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitals',
            new_name='Vital',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='price',
        ),
        migrations.RemoveField(
            model_name='test',
            name='type',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospitalitem'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospitalitem'),
        ),
        migrations.AddField(
            model_name='test',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospitalitem'),
        ),
    ]
