# Generated by Django 5.1.4 on 2025-02-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_patient_email_alter_patient_phone_and_more'),
        ('users', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='users.department'),
        ),
    ]
